import React, { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

// Auto-generated by: https://github.com/pmndrs/gltfjsx
export default function Model({ url, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(url)
  useFrame((state) => {
    group.current.children.forEach((child, index) => {
      child.position.y += Math.sin(index * 1000 + state.clock.elapsedTime) / 50
      child.rotation.x += (Math.sin(index * 1000 + state.clock.elapsedTime) * Math.PI) / 2000
      child.rotation.y += (Math.cos(index * 1000 + state.clock.elapsedTime) * Math.PI) / 3000
      child.rotation.z += (Math.sin(index * 1000 + state.clock.elapsedTime) * Math.PI) / 4000
    })
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.M_Curly}
        geometry={nodes.Curly.geometry}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[0, 0, 0]}
      />
      <mesh material={materials.M_DNA} geometry={nodes.DNA.geometry} position={[0, 0, 0]} rotation={[0, 0, 0]} />
      <mesh
        material={materials.M_Headphone}
        geometry={nodes.Headphones.geometry}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[0, 0, 0]}
      />
      <mesh
        material={materials.M_Notebook}
        geometry={nodes.Notebook.geometry}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[0, 0, 0]}
      />
      <mesh
        material={materials.M_Rocket}
        geometry={nodes.Rocket003.geometry}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[0, 0, 0]}
      />
      <mesh
        material={materials.M_Roundcube}
        geometry={nodes.Roundcube001.geometry}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[0, 0, 0]}
      />
      <mesh
        material={materials.M_Table}
        geometry={nodes.Table.geometry}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[0, 0, 0]}
      />
      <mesh
        material={materials.M_Headset}
        geometry={nodes.VR_Headset.geometry}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[0, 0, 0]}
      />
      <mesh
        material={materials.M_Zeppelin}
        geometry={nodes.Zeppelin.geometry}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[0, 0, 0]}
      />
    </group>
  )
}
